# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-05-22 02:10
from __future__ import unicode_literals

import backend.corpora.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=200)),
                ('generated', models.BooleanField(default=False)),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=50)),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('aliases', models.CharField(blank=True, max_length=500, null=True)),
                ('available', models.BooleanField(default=False)),
                ('generateable', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='ContentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=200)),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'Content Type',
                'verbose_name_plural': 'Content Types',
            },
        ),
        migrations.CreateModel(
            name='Corpus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=500)),
                ('date', models.DateTimeField()),
                ('xml', models.FileField(upload_to=backend.corpora.models.xml_upload_path)),
                ('url', models.URLField(blank=True)),
                ('author', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='author_corpus', to='corpora.Author')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='category_corpus', to='corpora.Category')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contenttype_corpus', to='corpora.ContentType')),
            ],
            options={
                'verbose_name': 'Corpus',
                'verbose_name_plural': 'Corpora',
            },
        ),
        migrations.CreateModel(
            name='GeneratedDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=500)),
                ('date', models.DateTimeField()),
                ('xml', models.FileField(upload_to=backend.corpora.models.xml_upload_path)),
                ('html_content', models.TextField()),
                ('image_url', models.URLField(blank=True)),
                ('image_credit', models.CharField(blank=True, max_length=200)),
                ('views', models.IntegerField(default=0)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author_generated', to='corpora.Author')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='category_generated', to='corpora.Category')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contenttype_generated', to='corpora.ContentType')),
                ('original_corpus', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='corpora.Corpus')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Outlet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=200)),
                ('website', models.URLField(blank=True)),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='generateddocument',
            name='outlet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='outlet_generated', to='corpora.Outlet'),
        ),
        migrations.AddField(
            model_name='corpus',
            name='outlet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='outlet_corpus', to='corpora.Outlet'),
        ),
        migrations.AddField(
            model_name='author',
            name='outlets',
            field=models.ManyToManyField(to='corpora.Outlet'),
        ),
    ]
