# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-01-17 10:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corpora', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='image_credit',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
