# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-01-15 09:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('corpora', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='likes',
            new_name='shares',
        ),
    ]
