# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-01-20 16:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('corpora', '0002_document_image_credit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='corpora.Author'),
        ),
    ]
