# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-01-15 10:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corpora', '0002_auto_20180115_0956'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='slug',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
