# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-01-15 10:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corpora', '0003_document_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='slug',
            field=models.CharField(blank=True, max_length=200, unique=True),
        ),
    ]
