# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-01-17 08:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corpora', '0004_auto_20180115_1007'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='available',
            field=models.BooleanField(default=False),
        ),
    ]
