# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-01-09 17:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0002_auto_20180109_1110'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='originial_url',
            new_name='original_url',
        ),
    ]
