# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-01-09 17:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0003_auto_20180109_1701'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='likes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='document',
            name='shares',
            field=models.IntegerField(default=0),
        ),
    ]
