# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-01-10 09:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0004_auto_20180109_1748'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='image_url',
            field=models.URLField(blank=True),
        ),
    ]
