# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-01-15 09:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0005_document_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='shares',
        ),
    ]
