# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-12-02 18:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generated', models.BooleanField(default=False)),
                ('headline', models.CharField(max_length=200, unique=True)),
                ('content_type', models.CharField(default='generic', max_length=20)),
                ('category', models.CharField(default='generic', max_length=20)),
                ('outlet', models.CharField(default='generic', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('entity_type', models.CharField(max_length=20)),
                ('salience', models.FloatField(null=True)),
                ('documents', models.ManyToManyField(to='mangler.Document')),
            ],
        ),
        migrations.CreateModel(
            name='EntityMetadata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mid', models.CharField(blank=True, max_length=10)),
                ('wikipedia_url', models.CharField(blank=True, max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Mention',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mention_type', models.CharField(max_length=20)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mangler.Entity')),
            ],
        ),
        migrations.CreateModel(
            name='PartOfSpeech',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=20)),
                ('pos', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Sentence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_offset', models.IntegerField()),
                ('document_index', models.IntegerField()),
                ('content', models.CharField(max_length=2000)),
                ('begin', models.IntegerField()),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mangler.Document')),
            ],
        ),
        migrations.CreateModel(
            name='Sentiment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(blank=True, null=True)),
                ('magnitude', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TextSpan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=200)),
                ('begin_offset', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lemma', models.CharField(max_length=100)),
                ('text', models.CharField(max_length=100)),
                ('text_begin', models.IntegerField()),
                ('document_index', models.IntegerField()),
                ('sentence_index', models.IntegerField()),
                ('edge_label', models.CharField(max_length=20)),
                ('edge_index', models.IntegerField()),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mangler.Document')),
                ('mention', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mangler.Mention')),
                ('part_of_speech', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mangler.PartOfSpeech')),
                ('sentence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mangler.Sentence')),
            ],
        ),
        migrations.AddField(
            model_name='sentence',
            name='sentiment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mangler.Sentiment'),
        ),
        migrations.AddField(
            model_name='mention',
            name='text',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mention', to='mangler.TextSpan'),
        ),
        migrations.AddField(
            model_name='entity',
            name='meta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mangler.EntityMetadata'),
        ),
        migrations.AddField(
            model_name='entity',
            name='sentiment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mangler.Sentiment'),
        ),
        migrations.AddField(
            model_name='document',
            name='sentiment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mangler.Sentiment'),
        ),
    ]
