# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-12-04 07:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mangler', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='textspan',
            name='vector',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='token',
            name='vector',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
