# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-12-31 10:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mangler', '0003_auto_20171204_0800'),
    ]

    operations = [
        migrations.AddField(
            model_name='entity',
            name='generated',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='document',
            name='headline',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='headline', to='mangler.Sentence', unique=True),
        ),
    ]
