# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-12-31 10:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mangler', '0004_auto_20171231_1005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='headline',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='headline', to='mangler.Sentence'),
        ),
    ]
