# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-01-03 14:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mangler', '0007_auto_20171231_1018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mention',
            name='text',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mention', to='mangler.TextSpan'),
        ),
    ]
