# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-01-03 18:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mangler', '0008_auto_20180103_1459'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sentence',
            name='content',
        ),
    ]
