# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-01-03 19:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mangler', '0009_remove_sentence_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='token',
            name='ent_iob',
            field=models.CharField(default='O', max_length=2),
            preserve_default=False,
        ),
    ]
