# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-01-05 21:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mangler', '0011_document_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='headline',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='headline', to='mangler.Sentence'),
        ),
    ]
