# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-12-04 08:00
from __future__ import unicode_literals

from django.db import migrations
import picklefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('mangler', '0002_auto_20171204_0755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textspan',
            name='vector',
            field=picklefield.fields.PickledObjectField(editable=False),
        ),
        migrations.AlterField(
            model_name='token',
            name='vector',
            field=picklefield.fields.PickledObjectField(default=[-0.0002, 0.004201], editable=False),
            preserve_default=False,
        ),
    ]
